USE UniformPolicyDB;

CREATE TABLE Users ( 
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(100) NOT NULL
);

CREATE TABLE Violations (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Date DATETIME NOT NULL,
    StudentID NVARCHAR(50)NOT NULL,
    Course NVARCHAR(100)NOT NULL,
    YearLevel NVARCHAR(50)NOT NULL,
    Violation NVARCHAR(500) NOT NULL
);